version: "3.7"

services:
  api:
    build: 
      "."
    container_name: node-app
    volumes:
      - ./.api:/home/node/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - ./.data:/var/lib/postgresql
    ports:
      - "5433:5432"
    restart: always
